version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
    version_requirement_updates: increase_versions
  - package_manager: javascript
    directory: /benchmarks
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
    version_requirement_updates: increase_versions
